

_ply = _this select 0;
_ply setVariable ["cqc_choke_tgt",objNull];
waitUntil {!isNull player && alive player};
[_ply,"CQC choke","","","(_this == _target) && !(isNull (_target getVariable 'cqc_choke_tgt')) && (_target getVariable 'cqc_choke_tgt') in attachedObjects _target", "true",{},{(_this select 0) playMove "AmovPercMstpSrasWpstDnon_SaluteOut";},{_tgt = (_this select 0) getVariable "cqc_choke_tgt"; [_tgt,true,60,true] remoteExec ["ace_medical_fnc_setUnconscious",_tgt]; (_this select 0) forceWalk false; _tgt attachTo [(_this select 0),[0,1,0]]; detach _tgt; (_this select 0) setVariable ["cqc_choke_tgt",objNull];},{},[],5,99,false,false ] call bis_fnc_holdActionAdd;
[_ply,"CQC throw","","","(_this == _target) && !(isNull (_target getVariable 'cqc_choke_tgt')) && (_target getVariable 'cqc_choke_tgt') in attachedObjects _target", "true",{},{(_this select 0) playMove "AmovPercMstpSrasWpstDnon_SaluteOut";},{_tgt = (_this select 0) getVariable "cqc_choke_tgt"; [_tgt,true,10,true] remoteExec ["ace_medical_fnc_setUnconscious",_tgt]; (_this select 0) forceWalk false; _tgt attachTo [(_this select 0),[0,1,0]]; detach _tgt; (_this select 0) setVariable ["cqc_choke_tgt",objNull]; if (cursorTarget distance (_this select 0)<2 && cursorTarget isKindOf "Man") then {[cursorTarget,true,10,true] remoteExec ["ace_medical_fnc_setUnconscious",cursorTarget];}},{},[],0.5,90,false,false ] call bis_fnc_holdActionAdd;


[(_this select 0), "CQC grab", "", "", "(_this == _target) && [_this,_target] call pequod_fnc_cqc_check", "([position  _target, (getDir _target),90,position (_target getVariable 'cqc_choke_tgt')] call BIS_fnc_inAngleSector)", {(_this select 0) setVariable ["cqc_choke_tgt", nearestObjects [_this select 0,['Man'],5] select 1] }, {_tgt = (_this select 0) getVariable "cqc_choke_tgt"; if (_tgt distance (_this select 0)<2) then { _tgt setDir getDir (_this select 0)};}, {_tgt = (_this select 0) getVariable "cqc_choke_tgt"; if (_tgt distance (_this select 0)<2) then {(_this select 0) getVariable "cqc_choke_tgt" attachTo [(_this select 0),[0,0.5,0]]; if (!( cursorObject getVariable "ACE_isUnconscious")) then { [(_this select 0) getVariable "cqc_choke_tgt","acts_onchair_dead"] remoteExec ["switchMove",_tgt]}; (_this select 0) forceWalk true; [_this select 0,_tgt] spawn {_ply = _this select 0; _tgt = _this select 1; waitUntil {(!alive _tgt || !alive _ply || isNull (_ply getVariable 'cqc_choke_tgt'))}; if (!alive _ply || !alive _tgt) then { detach _tgt; _ply forceWalk false; _ply setVariable ["cqc_choke_tgt",objNull]; [_tgt,""] remoteExec ["SwitchMove",_tgt];}};} else {(_this select 0) setVariable ["cqc_choke_tgt",objNull]}}, {(_this select 0) setVariable ["cqc_choke_tgt",objNull]; }, [], 0.5, 99, false, false] call bis_fnc_holdActionAdd; 
_this select 0 addAction ["CQC let go",{_tgt = (_this select 0) getVariable "cqc_choke_tgt"; _tgt attachTo [_this select 0,[0,1,0]]; detach _tgt; (_this select 0) setVariable ["cqc_choke_tgt",objNull]; (_this select 0) forceWalk false; if (!(_tgt getVariable "ACE_isUnconscious")) then {[_tgt,""] remoteExec ["switchMove",_tgt]};},[],1,false,true,"","!(isNull ((_target) getVariable 'cqc_choke_tgt'))"];
